import { Layoutt } from "./component/Layoutt";
import Head from "next/head";
import Image from "next/image";
import sir from "../public/images/profile/sir.jpg"
import { AnimationT } from "./component/AnimationT";


export default function Home() {
  return (
    <>
      <Head>
        <title>Sajal Mukhopadhyay</title>
        <meta name="description" content="Generated by create next app" />


      </Head>

      <main className="flex items-center text-dark w-full min-h-screen">
        <Layoutt className="pt-0">
          <div className="flex items-center justify-betweenw-full">
            <div className="col-span-3 relative w-max h-max rounded-2xl border-solid border-dark
          bg-light p-8">
              <div className="absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark" />
              <div className="w-max">
                <Image src={sir} alt='sir' className="w-max h-max rounded-xl" />
              </div>
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimationT text='Dr.Sajal Mukhopadhyay' className="" />
              <AnimationT text='Associate Professor' className="!text-3xl " />
              <AnimationT text='sajal[at]cse[dot]nitdgp[dot]ac[dot]in' className="!text-xl " />

              <p></p>

            </div>
          </div>
        </Layoutt>
      </main>

    </>
  )
}